-- RBAC (Role-Based Access Control) System Schema
-- This migration creates tables for user authentication and permission management

-- ============================================
-- Table 1: RBAC Users (System Users for Authentication)
-- ============================================
CREATE TABLE IF NOT EXISTS rbac_users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    is_admin BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

-- ============================================
-- Table 2: RBAC Permissions (Available Pages/Routes)
-- ============================================
CREATE TABLE IF NOT EXISTS rbac_permissions (
    permission_id SERIAL PRIMARY KEY,
    route_name VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- Table 3: RBAC User Permissions (Junction Table)
-- ============================================
CREATE TABLE IF NOT EXISTS rbac_user_permissions (
    user_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by INTEGER,
    PRIMARY KEY (user_id, permission_id),
    FOREIGN KEY (user_id) REFERENCES rbac_users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES rbac_permissions(permission_id) ON DELETE CASCADE,
    FOREIGN KEY (granted_by) REFERENCES rbac_users(user_id) ON DELETE SET NULL
);

-- ============================================
-- Indexes for better performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_rbac_users_username ON rbac_users(username);
CREATE INDEX IF NOT EXISTS idx_rbac_users_email ON rbac_users(email);
CREATE INDEX IF NOT EXISTS idx_rbac_users_is_admin ON rbac_users(is_admin);
CREATE INDEX IF NOT EXISTS idx_rbac_permissions_route ON rbac_permissions(route_name);
CREATE INDEX IF NOT EXISTS idx_rbac_user_permissions_user ON rbac_user_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_rbac_user_permissions_permission ON rbac_user_permissions(permission_id);

-- ============================================
-- Insert default admin user (password: admin123)
-- Note: The password hash will be generated by Python on first run
-- Run the setup_rbac.py script to create the admin user with proper password hash
-- ============================================

-- ============================================
-- Insert default permissions (all available routes)
-- ============================================
INSERT INTO rbac_permissions (route_name, display_name, description, category) VALUES
('index', 'Dashboard', 'View dashboard with statistics', 'Main'),
('users_list', 'Users List', 'View list of all users', 'Users'),
('user_create', 'Create User', 'Create new user records', 'Users'),
('workshops_view', 'Workshops', 'View workshop data and time slots', 'Workshops'),
('team_building_list', 'Team Building', 'View team building records', 'Team Building'),
('team_building_create', 'Create Team Building', 'Create team building records', 'Team Building'),
('blog_submissions_list', 'Blog Submissions', 'View blog submission records', 'Blog Submissions'),
('blog_submission_create', 'Create Blog Submission', 'Create blog submission records', 'Blog Submissions'),
('logs_list', 'Activity Logs', 'View activity logs', 'Logs'),
('import_page', 'Import Data', 'Import data from Excel files', 'Import'),
('import_master_page', 'Master Workbook Import', 'Import master workbook with 12 sheets', 'Import'),
('import_advanced_page', 'Single Table Import', 'Import single table data', 'Import')
ON CONFLICT (route_name) DO NOTHING;

-- ============================================
-- Grant all permissions to admin user
-- ============================================
INSERT INTO rbac_user_permissions (user_id, permission_id, granted_by)
SELECT 
    (SELECT user_id FROM rbac_users WHERE username = 'admin' LIMIT 1),
    permission_id,
    (SELECT user_id FROM rbac_users WHERE username = 'admin' LIMIT 1)
FROM rbac_permissions
ON CONFLICT DO NOTHING;

